version: '3.9'

services:
  client:
    container_name: react-app-git-finder
    restart: always
    build: ./front
    ports:
      - '3000:3000/tcp'
    expose:
      - 3000

  api:
    container_name: api-git-finder
    restart: always
    build: ./back
    ports:
      - '8080:8080/tcp'
    links:
      - 'db:db'
      - 'cache:cache'
    expose:
      - 8080
    environment:
      APP_PORT: 8080
      DATABASE_CONNECTION_STRING: postgres://root:root@db:5432/root
      REDIS_CONNECTION_STRING: redis://cache:6379/1
      NODE_ENV: DEV
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  db:
    image: postgres
    container_name: postgres-git-finder
    restart: always
    ports:
      - '5433:5432'
    expose:
      - 5433
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  cache:
    image: redis:6.2-alpine
    container_name: cache-git-finder
    restart: always
    ports:
      - '6380:6379'
    expose:
      - 6380
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
